version: "3"

volumes:
  home-db-vol:
    driver: local
  home-redis-vol:
    driver: local

networks:
  home-net:

services:
  web:
    build:
      context: ./nginx
    image: home-web
    container_name: home-web
    volumes:
      - ../:/var/www/home
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fpm
    links:
      - fpm
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - home-net

  fpm:
    build:
      context: ./web
    container_name: home-fpm
    image: home-php
    ports:
      - 9000:9000
    volumes:
      - ./web/php/php.ini:/etc/php/conf.d/php.ini
      - ./web/php/dev.ini:/etc/php/conf.d/dev.ini
      - ./web/php-fpm/web.conf:/etc/php-fpm.d/www.conf
    depends_on:
      - mysql
      - redis
    restart: on-failure
    networks:
      - home-net

  mysql:
    build:
      context: ./mysql
    image: home-mysql
    container_name: home-mysql
    volumes:
      - home-db-vol:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=db
    ports:
      - "3306:3306"
    networks:
      - home-net
    restart: on-failure

  redis:
    build:
      context: ./redis
    container_name: home-redis
    image: home-redis
    ports:
      - "6379:6379"
    volumes:
      - home-redis-vol:/var/lib/redis/
    networks:
      - home-net
    restart: on-failure